"""Insert theory-driven predictive model cells into the notebook."""
import json, shutil

shutil.copy('the model.ipynb', 'the model.ipynb.bak2')

with open('the model.ipynb') as f:
    nb = json.load(f)

def mkmd(src):
    return {"cell_type": "markdown", "metadata": {}, "source": src}

def mkcode(src):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": src}

# --- New cells ---

md_header = mkmd([
    "## 6.6 Theory-Driven Predictive Model (Issue Ownership + Margin Regression)\n",
    "\n",
    "The model above predicts the **binary winner** and barely beats the majority-class baseline (Republicans won 31/51 states+DC in 2024, so trivially predicting \"R\" gives ~63%). That is not a meaningful answer to our research question.\n",
    "\n",
    "Our RQ asks: *\"To what extent do state-level issue salience profiles — defined by the dominant policy concerns driving voter behavior — predict partisan electoral outcomes across U.S. states in presidential elections?\"*\n",
    "\n",
    "To answer this rigorously, we make three changes grounded in our theoretical framework (Petrocik 1996; Egan 2013):\n",
    "\n",
    "**1. Operationalize issue ownership theory.** Petrocik argues parties develop long-term reputations for competence on specific issues. We map each discovered political topic to the party that \"owns\" it in the U.S. context and compute a **Party-Issue Salience Index (PISI)** per state — the net salience of Democrat-owned vs Republican-owned issues. Sentiment-weighted variants distinguish *favorable* salience from *hostile* salience.\n",
    "\n",
    "**2. Predict vote margin, not binary winner.** The continuous two-party R–D margin preserves the full signal (California D+19 and Vermont D+23 are both \"D\" but very different). It also matches one of our originally-proposed RQ formulations (*\"… predict two-party presidential vote share margins…\"*).\n",
    "\n",
    "**3. Test incremental signal via nested baselines.** The single strongest predictor of 2024 state margins is the 2020 margin. Any honest test of \"does Twitter discourse add information?\" must control for prior voting behavior and structural demographics. We compare:\n",
    "\n",
    "- **M0**: intercept only (predict mean margin)\n",
    "- **M1**: 2020 margin only\n",
    "- **M2**: M1 + demographics (% bachelor's degree, % non-Hispanic white)\n",
    "- **M3**: M2 + Twitter features (PISI, sentiment-weighted PISI, LLM stance lean, mean state sentiment, per-issue salience)\n",
    "\n",
    "If M3 → M2 R² gain is positive and the bootstrapped 95% CI excludes zero, **state-level issue salience adds genuine predictive power beyond what is already encoded in past behavior and demographic structure** — a direct affirmative answer to our RQ. If not, we have the equally important (and audit-relevant) finding that the *predictive* value of Twitter discourse is largely redundant with structural variables."
])

code_features = mkcode([
    "# --- Petrocik issue ownership mapping ---\n",
    "# Based on Petrocik (1996), Egan (2013), and U.S.-specific issue-ownership literature.\n",
    "# D-owned: parties associated with competence on social/welfare/regulatory issues.\n",
    "# R-owned: parties associated with competence on order/security/economic-liberty issues.\n",
    "issue_ownership = {\n",
    "    'Healthcare':                     'D',\n",
    "    'Climate / Environment':          'D',\n",
    "    'Education':                      'D',\n",
    "    'Abortion / Reproductive Rights': 'D',\n",
    "    'Immigration / Border':           'R',\n",
    "    'Gun Policy':                     'R',\n",
    "    'Economic Policy':                'R',\n",
    "    'Criminal Justice':               'R',\n",
    "    'Foreign Policy':                 'R',\n",
    "    'Middle East / Israel-Gaza':      'CONTESTED',\n",
    "    'Partisan Discourse':             'CONTESTED',\n",
    "    '2024 Election / Candidates':     'CONTESTED',\n",
    "}\n",
    "\n",
    "# --- 2020 two-party margin (R - D, percentage points) ---\n",
    "# Source: certified state results, Federal Election Commission.\n",
    "margin_2020 = {\n",
    "    'AL':  25.5, 'AK':  10.1, 'AZ':  -0.3, 'AR':  27.6, 'CA': -29.2, 'CO': -13.5,\n",
    "    'CT': -20.0, 'DE': -19.0, 'DC': -86.8, 'FL':   3.4, 'GA':  -0.2, 'HI': -29.5,\n",
    "    'ID':  30.8, 'IL': -17.0, 'IN':  16.1, 'IA':   8.2, 'KS':  14.6, 'KY':  25.9,\n",
    "    'LA':  18.6, 'ME':  -9.1, 'MD': -33.2, 'MA': -33.5, 'MI':  -2.8, 'MN':  -7.1,\n",
    "    'MS':  16.5, 'MO':  15.4, 'MT':  16.4, 'NE':  19.1, 'NV':  -2.4, 'NH':  -7.3,\n",
    "    'NJ': -15.9, 'NM': -10.8, 'NY': -23.1, 'NC':   1.3, 'ND':  33.4, 'OH':   8.0,\n",
    "    'OK':  33.1, 'OR': -16.1, 'PA':  -1.2, 'RI': -20.7, 'SC':  11.7, 'SD':  26.2,\n",
    "    'TN':  23.2, 'TX':   5.6, 'UT':  20.5, 'VT': -35.1, 'VA': -10.1, 'WA': -19.2,\n",
    "    'WV':  38.9, 'WI':  -0.6, 'WY':  43.3,\n",
    "}\n",
    "\n",
    "# --- Structural demographics (% bachelor's+, % non-Hispanic white) ---\n",
    "# Source: U.S. Census Bureau ACS 5-year estimates.\n",
    "demographics_data = {\n",
    "    'AL': (26.2, 64.6), 'AK': (30.7, 59.4), 'AZ': (30.7, 53.4), 'AR': (24.2, 70.8),\n",
    "    'CA': (35.3, 35.2), 'CO': (43.2, 66.4), 'CT': (40.6, 63.2), 'DE': (33.0, 60.8),\n",
    "    'DC': (60.6, 36.8), 'FL': (31.1, 51.6), 'GA': (32.0, 50.0), 'HI': (33.6, 21.4),\n",
    "    'ID': (28.7, 80.4), 'IL': (36.0, 60.2), 'IN': (27.8, 78.0), 'IA': (29.7, 84.5),\n",
    "    'KS': (34.5, 75.4), 'KY': (25.4, 82.6), 'LA': (25.2, 57.8), 'ME': (33.2, 90.6),\n",
    "    'MD': (41.6, 47.8), 'MA': (45.3, 67.6), 'MI': (30.5, 73.0), 'MN': (37.5, 76.6),\n",
    "    'MS': (23.2, 55.4), 'MO': (30.0, 77.6), 'MT': (33.2, 85.4), 'NE': (32.4, 76.4),\n",
    "    'NV': (26.4, 45.6), 'NH': (38.4, 87.4), 'NJ': (41.2, 53.2), 'NM': (29.2, 35.4),\n",
    "    'NY': (38.2, 53.8), 'NC': (33.0, 60.6), 'ND': (32.0, 82.0), 'OH': (29.8, 76.0),\n",
    "    'OK': (26.7, 62.0), 'OR': (35.2, 73.6), 'PA': (33.8, 73.6), 'RI': (35.7, 70.4),\n",
    "    'SC': (30.0, 62.8), 'SD': (30.6, 80.4), 'TN': (29.8, 71.4), 'TX': (32.3, 39.0),\n",
    "    'UT': (37.0, 75.2), 'VT': (41.0, 89.0), 'VA': (40.6, 59.0), 'WA': (38.3, 65.8),\n",
    "    'WV': (23.4, 91.0), 'WI': (32.0, 79.6), 'WY': (28.6, 82.4),\n",
    "}\n",
    "\n",
    "# --- Per-state topic salience (% of political tweets in each topic) ---\n",
    "topic_share = (df_pol_states\n",
    "    .groupby(['state_code', 'topic_label'])\n",
    "    .size()\n",
    "    .unstack(fill_value=0))\n",
    "row_sums = topic_share.sum(axis=1).replace(0, 1)\n",
    "topic_share = topic_share.div(row_sums, axis=0)\n",
    "\n",
    "# --- Per-state, per-topic mean sentiment (for sentiment-weighted PISI) ---\n",
    "df_pol_sent_full = df_pol_states.copy()\n",
    "df_pol_sent_full['vader_compound'] = df_sample.loc[df_pol_sent_full.index, 'vader_compound']\n",
    "sent_state_topic = (df_pol_sent_full\n",
    "    .groupby(['state_code', 'topic_label'])['vader_compound']\n",
    "    .mean()\n",
    "    .unstack(fill_value=0))\n",
    "\n",
    "# --- Build PISI features ---\n",
    "d_topics = [c for c in topic_share.columns if issue_ownership.get(c) == 'D']\n",
    "r_topics = [c for c in topic_share.columns if issue_ownership.get(c) == 'R']\n",
    "print(f'D-owned topics observed: {d_topics}')\n",
    "print(f'R-owned topics observed: {r_topics}')\n",
    "\n",
    "pisi_raw = topic_share[d_topics].sum(axis=1) - topic_share[r_topics].sum(axis=1)\n",
    "\n",
    "# Sentiment-weighted: D-issues weighted by their positive sentiment minus R-issues weighted by their positive sentiment.\n",
    "# Positive sentiment on a D-owned issue is interpreted as the D-frame resonating.\n",
    "sent_aligned_d = sent_state_topic.reindex(columns=d_topics, fill_value=0).reindex(index=topic_share.index, fill_value=0)\n",
    "sent_aligned_r = sent_state_topic.reindex(columns=r_topics, fill_value=0).reindex(index=topic_share.index, fill_value=0)\n",
    "pisi_weighted = ((topic_share[d_topics] * sent_aligned_d).sum(axis=1)\n",
    "                 - (topic_share[r_topics] * sent_aligned_r).sum(axis=1))\n",
    "\n",
    "# --- LLM stance lean per state (net D - R share) ---\n",
    "df_llm_geo = df_llm.dropna(subset=['state_code']).copy()\n",
    "stance_pivot = (df_llm_geo.groupby(['state_code', 'stance_label']).size().unstack(fill_value=0))\n",
    "stance_total = stance_pivot.sum(axis=1).replace(0, 1)\n",
    "stance_lean = ((stance_pivot.get('supports Democratic party', 0) - stance_pivot.get('supports Republican party', 0))\n",
    "               / stance_total)\n",
    "\n",
    "# --- Mean overall state sentiment ---\n",
    "mean_state_sent = df_sample.dropna(subset=['state_code']).groupby('state_code')['vader_compound'].mean()\n",
    "\n",
    "print(f'\\nPISI built for {pisi_raw.notna().sum()} states.')\n",
    "print(f'PISI range: [{pisi_raw.min():.3f}, {pisi_raw.max():.3f}], mean={pisi_raw.mean():.3f}')\n"
])

code_matrix = mkcode([
    "# --- Build the extended feature matrix ---\n",
    "states = sorted(set(df_model['state_code']) & set(margin_2020) & set(demographics_data))\n",
    "rows = []\n",
    "for s in states:\n",
    "    row = df_model.loc[df_model['state_code'] == s].iloc[0]\n",
    "    bach, white = demographics_data[s]\n",
    "    rec = {\n",
    "        'state_code':     s,\n",
    "        'margin_2024':    row['margin_r'],          # outcome (R - D, pp)\n",
    "        'margin_2020':    margin_2020[s],           # baseline\n",
    "        'pct_bachelor':   bach,\n",
    "        'pct_white':      white,\n",
    "        'pisi':           pisi_raw.get(s, 0.0),\n",
    "        'pisi_weighted':  pisi_weighted.get(s, 0.0),\n",
    "        'stance_lean':    stance_lean.get(s, 0.0),\n",
    "        'mean_sentiment': mean_state_sent.get(s, 0.0),\n",
    "    }\n",
    "    # Per-issue salience (only owned topics)\n",
    "    for c in d_topics + r_topics:\n",
    "        rec[f'sal_{c}'] = topic_share.loc[s, c] if s in topic_share.index else 0.0\n",
    "    rows.append(rec)\n",
    "\n",
    "df_ext = pd.DataFrame(rows).set_index('state_code')\n",
    "df_ext = df_ext.replace([np.inf, -np.inf], 0).fillna(0)\n",
    "\n",
    "print(f'Extended feature matrix: {df_ext.shape[0]} states x {df_ext.shape[1]-1} features')\n",
    "print(f'Outcome (margin_2024): min={df_ext[\"margin_2024\"].min():.1f}, max={df_ext[\"margin_2024\"].max():.1f}, mean={df_ext[\"margin_2024\"].mean():.1f}, std={df_ext[\"margin_2024\"].std():.1f}')\n",
    "\n",
    "# Show the 2020->2024 raw relationship\n",
    "from scipy.stats import pearsonr\n",
    "r20, p20 = pearsonr(df_ext['margin_2020'], df_ext['margin_2024'])\n",
    "print(f'\\nRaw correlation, 2020 margin <-> 2024 margin: r={r20:.3f} (p={p20:.2e})')\n",
    "print(f'Raw correlation, PISI <-> 2024 margin:        r={pearsonr(df_ext[\"pisi\"], df_ext[\"margin_2024\"])[0]:.3f}')\n",
    "print(f'Raw correlation, stance lean <-> 2024 margin: r={pearsonr(df_ext[\"stance_lean\"], df_ext[\"margin_2024\"])[0]:.3f}')\n"
])

code_models = mkcode([
    "# --- Nested model comparison with LOOCV + bootstrapped 95% CIs ---\n",
    "from sklearn.linear_model import Ridge\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.pipeline import Pipeline\n",
    "from sklearn.model_selection import LeaveOneOut\n",
    "from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error\n",
    "\n",
    "y_ext = df_ext['margin_2024'].values\n",
    "twitter_feats = ['pisi', 'pisi_weighted', 'stance_lean', 'mean_sentiment'] + [c for c in df_ext.columns if c.startswith('sal_')]\n",
    "\n",
    "feature_sets = {\n",
    "    'M0 (intercept only)':            [],\n",
    "    'M1 (2020 margin)':               ['margin_2020'],\n",
    "    'M2 (2020 + demographics)':       ['margin_2020', 'pct_bachelor', 'pct_white'],\n",
    "    'M3 (M2 + Twitter features)':     ['margin_2020', 'pct_bachelor', 'pct_white'] + twitter_feats,\n",
    "    'M3-only (Twitter alone)':        twitter_feats,\n",
    "}\n",
    "\n",
    "def loocv_predict(X, y, alpha=1.0):\n",
    "    if X.shape[1] == 0:\n",
    "        return np.full_like(y, y.mean(), dtype=float)\n",
    "    loo = LeaveOneOut()\n",
    "    preds = np.zeros(len(y))\n",
    "    for tr, te in loo.split(X):\n",
    "        pipe = Pipeline([('sc', StandardScaler()), ('rg', Ridge(alpha=alpha, random_state=RANDOM_STATE))])\n",
    "        pipe.fit(X[tr], y[tr])\n",
    "        preds[te] = pipe.predict(X[te])\n",
    "    return preds\n",
    "\n",
    "def metrics(y, preds):\n",
    "    return {\n",
    "        'r2':         r2_score(y, preds),\n",
    "        'rmse':       float(np.sqrt(mean_squared_error(y, preds))),\n",
    "        'mae':        mean_absolute_error(y, preds),\n",
    "        'r':          float(np.corrcoef(y, preds)[0, 1]) if preds.std() > 0 else 0.0,\n",
    "        'binary_acc': float(np.mean(np.sign(preds) == np.sign(y))),\n",
    "    }\n",
    "\n",
    "# Tune alpha per model on a small grid using LOOCV R^2\n",
    "def best_alpha(X, y, grid=(0.1, 1.0, 5.0, 10.0, 25.0, 50.0)):\n",
    "    if X.shape[1] == 0: return 0.0\n",
    "    best, best_r2 = grid[0], -np.inf\n",
    "    for a in grid:\n",
    "        p = loocv_predict(X, y, alpha=a)\n",
    "        r2 = r2_score(y, p)\n",
    "        if r2 > best_r2:\n",
    "            best, best_r2 = a, r2\n",
    "    return best\n",
    "\n",
    "results_ext = {}\n",
    "for name, feats in feature_sets.items():\n",
    "    X = df_ext[feats].values if feats else np.zeros((len(y_ext), 0))\n",
    "    alpha = best_alpha(X, y_ext) if feats else 0.0\n",
    "    preds = loocv_predict(X, y_ext, alpha=alpha)\n",
    "    m = metrics(y_ext, preds)\n",
    "    m['alpha'] = alpha\n",
    "    m['preds'] = preds\n",
    "    m['feats'] = feats\n",
    "    results_ext[name] = m\n",
    "\n",
    "# Bootstrap CIs on R^2 for M2 and M3\n",
    "def bootstrap_r2(feats, y, n_boot=500, seed=42):\n",
    "    if not feats:\n",
    "        return (np.nan, np.nan)\n",
    "    rng = np.random.RandomState(seed)\n",
    "    n = len(y)\n",
    "    Xall = df_ext[feats].values\n",
    "    alpha = best_alpha(Xall, y)\n",
    "    r2s = []\n",
    "    for _ in range(n_boot):\n",
    "        idx = rng.choice(n, n, replace=True)\n",
    "        if len(np.unique(idx)) < 10:\n",
    "            continue\n",
    "        try:\n",
    "            p = loocv_predict(Xall[idx], y[idx], alpha=alpha)\n",
    "            r2s.append(r2_score(y[idx], p))\n",
    "        except Exception:\n",
    "            continue\n",
    "    return (float(np.percentile(r2s, 2.5)), float(np.percentile(r2s, 97.5)))\n",
    "\n",
    "ci_m1 = bootstrap_r2(feature_sets['M1 (2020 margin)'], y_ext, 300)\n",
    "ci_m2 = bootstrap_r2(feature_sets['M2 (2020 + demographics)'], y_ext, 300)\n",
    "ci_m3 = bootstrap_r2(feature_sets['M3 (M2 + Twitter features)'], y_ext, 300)\n",
    "\n",
    "# Bootstrap the *incremental* R^2 (M3 - M2) by resampling jointly\n",
    "def bootstrap_incremental(feats_a, feats_b, y, n_boot=500, seed=42):\n",
    "    rng = np.random.RandomState(seed)\n",
    "    n = len(y)\n",
    "    Xa = df_ext[feats_a].values\n",
    "    Xb = df_ext[feats_b].values\n",
    "    aa = best_alpha(Xa, y); ab = best_alpha(Xb, y)\n",
    "    diffs = []\n",
    "    for _ in range(n_boot):\n",
    "        idx = rng.choice(n, n, replace=True)\n",
    "        if len(np.unique(idx)) < 10: continue\n",
    "        try:\n",
    "            r2a = r2_score(y[idx], loocv_predict(Xa[idx], y[idx], alpha=aa))\n",
    "            r2b = r2_score(y[idx], loocv_predict(Xb[idx], y[idx], alpha=ab))\n",
    "            diffs.append(r2b - r2a)\n",
    "        except Exception:\n",
    "            continue\n",
    "    return (float(np.percentile(diffs, 2.5)), float(np.percentile(diffs, 97.5)), float(np.mean(diffs)))\n",
    "\n",
    "inc_lo, inc_hi, inc_mean = bootstrap_incremental(\n",
    "    feature_sets['M2 (2020 + demographics)'],\n",
    "    feature_sets['M3 (M2 + Twitter features)'],\n",
    "    y_ext, n_boot=300)\n",
    "\n",
    "# Print results\n",
    "print('=' * 90)\n",
    "print('NESTED MODEL COMPARISON  (LOOCV, Ridge regression on 2024 R-D margin)')\n",
    "print('=' * 90)\n",
    "print(f'n = {len(y_ext)} states (incl. DC).  Target std = {y_ext.std():.1f} pp.')\n",
    "print(f'{\"Model\":<32} {\"R²\":>7} {\"RMSE\":>7} {\"MAE\":>7} {\"r\":>6} {\"BinAcc\":>8} {\"alpha\":>7}')\n",
    "print('-' * 90)\n",
    "for name, m in results_ext.items():\n",
    "    print(f'{name:<32} {m[\"r2\"]:>7.3f} {m[\"rmse\"]:>7.2f} {m[\"mae\"]:>7.2f} {m[\"r\"]:>6.3f} {m[\"binary_acc\"]:>8.3f} {m[\"alpha\"]:>7.2f}')\n",
    "print('=' * 90)\n",
    "print()\n",
    "print('Bootstrap 95% CI on R²:')\n",
    "print(f'  M1: [{ci_m1[0]:.3f}, {ci_m1[1]:.3f}]')\n",
    "print(f'  M2: [{ci_m2[0]:.3f}, {ci_m2[1]:.3f}]')\n",
    "print(f'  M3: [{ci_m3[0]:.3f}, {ci_m3[1]:.3f}]')\n",
    "print()\n",
    "print('Incremental R² from adding Twitter features (M3 - M2):')\n",
    "delta = results_ext['M3 (M2 + Twitter features)']['r2'] - results_ext['M2 (2020 + demographics)']['r2']\n",
    "print(f'  Point estimate: {delta:+.3f}')\n",
    "print(f'  Bootstrap mean: {inc_mean:+.3f}')\n",
    "print(f'  Bootstrap 95% CI: [{inc_lo:+.3f}, {inc_hi:+.3f}]')\n",
    "print()\n",
    "majority_baseline = max((y_ext > 0).mean(), (y_ext <= 0).mean())\n",
    "print(f'Majority-class binary baseline: {majority_baseline:.3f}')\n",
    "print(f'M3 binary accuracy:             {results_ext[\"M3 (M2 + Twitter features)\"][\"binary_acc\"]:.3f}')\n"
])

code_viz = mkcode([
    "# --- Visualization: predicted vs actual margin & standardized coefficients ---\n",
    "import plotly.graph_objects as go\n",
    "from plotly.subplots import make_subplots\n",
    "\n",
    "m3 = results_ext['M3 (M2 + Twitter features)']\n",
    "m2 = results_ext['M2 (2020 + demographics)']\n",
    "feats_m3 = m3['feats']\n",
    "\n",
    "# Fit M3 on full data for coefficients\n",
    "pipe = Pipeline([('sc', StandardScaler()), ('rg', Ridge(alpha=m3['alpha'], random_state=RANDOM_STATE))])\n",
    "pipe.fit(df_ext[feats_m3].values, y_ext)\n",
    "coefs = pipe.named_steps['rg'].coef_\n",
    "coef_df = pd.DataFrame({'feature': feats_m3, 'coef': coefs}).reindex(columns=['feature', 'coef'])\n",
    "coef_df['abs'] = coef_df['coef'].abs()\n",
    "coef_df = coef_df.sort_values('coef')\n",
    "\n",
    "fig = make_subplots(rows=1, cols=2, subplot_titles=(\n",
    "    f'M3 Predicted vs Actual 2024 Margin (R² = {m3[\"r2\"]:.3f})',\n",
    "    'M3 Standardized Coefficients (sign = direction toward Republican margin)'\n",
    "), column_widths=[0.5, 0.5])\n",
    "\n",
    "fig.add_trace(go.Scatter(\n",
    "    x=y_ext, y=m3['preds'], mode='markers+text',\n",
    "    text=list(df_ext.index), textposition='top center', textfont=dict(size=9),\n",
    "    marker=dict(size=10, color=y_ext, colorscale='RdBu_r', cmid=0, line=dict(width=1, color='black')),\n",
    "    showlegend=False, name='states'\n",
    "), row=1, col=1)\n",
    "lim = float(max(abs(y_ext).max(), abs(m3['preds']).max())) * 1.15\n",
    "fig.add_trace(go.Scatter(x=[-lim, lim], y=[-lim, lim], mode='lines',\n",
    "                          line=dict(dash='dash', color='gray'), showlegend=False, name='y=x'), row=1, col=1)\n",
    "fig.update_xaxes(title='Actual 2024 margin (R - D, pp)', row=1, col=1)\n",
    "fig.update_yaxes(title='Predicted margin', row=1, col=1)\n",
    "\n",
    "fig.add_trace(go.Bar(\n",
    "    y=coef_df['feature'], x=coef_df['coef'], orientation='h',\n",
    "    marker=dict(color=['#d62728' if c > 0 else '#1f77b4' for c in coef_df['coef']]),\n",
    "    showlegend=False\n",
    "), row=1, col=2)\n",
    "fig.update_xaxes(title='Standardized coefficient', row=1, col=2)\n",
    "fig.update_layout(height=max(600, 22 * len(feats_m3)), width=1500,\n",
    "                  title_text='Theory-Driven Margin Regression', showlegend=False)\n",
    "fig.show(renderer='notebook')\n",
    "\n",
    "# Per-state residuals: where the model is most wrong\n",
    "resid = pd.DataFrame({'state': df_ext.index, 'actual': y_ext, 'pred_m3': m3['preds'], 'pred_m2': m2['preds']})\n",
    "resid['resid_m3'] = resid['actual'] - resid['pred_m3']\n",
    "resid['abs_resid_m3'] = resid['resid_m3'].abs()\n",
    "print('\\nLargest M3 residuals (where Twitter+demographics model misses most):')\n",
    "print(resid.nlargest(10, 'abs_resid_m3')[['state', 'actual', 'pred_m3', 'resid_m3']].to_string(index=False))\n"
])

code_findings = mkcode([
    "# --- Auto-generated interpretation of the answer to our RQ ---\n",
    "m1r = results_ext['M1 (2020 margin)']['r2']\n",
    "m2r = results_ext['M2 (2020 + demographics)']['r2']\n",
    "m3r = results_ext['M3 (M2 + Twitter features)']['r2']\n",
    "m3o = results_ext['M3-only (Twitter alone)']['r2']\n",
    "delta = m3r - m2r\n",
    "\n",
    "print('=' * 78)\n",
    "print('ANSWER TO RESEARCH QUESTION')\n",
    "print('=' * 78)\n",
    "print('RQ: To what extent do state-level issue salience profiles predict')\n",
    "print('    partisan electoral outcomes across U.S. states?')\n",
    "print()\n",
    "print(f'  - 2020 vote margin alone explains          R² = {m1r:.3f}  ({m1r*100:.1f}% of variance)')\n",
    "print(f'  - Adding demographics raises this to       R² = {m2r:.3f}')\n",
    "print(f'  - Adding Twitter issue-salience features:  R² = {m3r:.3f}')\n",
    "print(f'  - Twitter features alone (no structural):  R² = {m3o:.3f}')\n",
    "print()\n",
    "print(f'  INCREMENTAL R² from Twitter (M3 - M2):     {delta:+.3f}')\n",
    "print(f'  95% CI on incremental R²:                 [{inc_lo:+.3f}, {inc_hi:+.3f}]')\n",
    "print()\n",
    "if inc_lo > 0:\n",
    "    verdict = ('AFFIRMATIVE: state-level issue salience adds genuine predictive\\n'\n",
    "               '  power BEYOND prior voting behavior and demographics. The 95% CI on the\\n'\n",
    "               '  incremental R² excludes zero, consistent with issue ownership theory\\n'\n",
    "               '  (Petrocik 1996): the policy-issue composition of state-level political\\n'\n",
    "               '  discourse carries information about partisan electoral outcomes that is\\n'\n",
    "               '  not already encoded in past behavior or demographic structure.')\n",
    "elif inc_hi < 0:\n",
    "    verdict = ('NEGATIVE: adding Twitter features REDUCES out-of-sample performance.\\n'\n",
    "               '  The Twitter signal is either too noisy or too biased relative to the\\n'\n",
    "               '  state-level outcome to add predictive value once 2020 voting and\\n'\n",
    "               '  demographics are accounted for. This is a substantive finding: the\\n'\n",
    "               '  predictive value of social media discourse is not just redundant with\\n'\n",
    "               '  structural variables but actively harmful when treated as signal.')\n",
    "else:\n",
    "    verdict = ('INCONCLUSIVE / REDUNDANT: Twitter issue-salience features do not add\\n'\n",
    "               '  statistically reliable predictive power beyond what is already captured\\n'\n",
    "               '  by prior voting behavior and demographics. The 95% CI on the incremental\\n'\n",
    "               '  R² includes zero. Twitter features ALONE do explain substantial variance\\n'\n",
    "               f'  (R² = {m3o:.3f}), but that signal is largely COLLINEAR with structural\\n'\n",
    "               '  features. This is itself an important audit-relevant finding: what looks\\n'\n",
    "               '  like Twitter signal is often demographic signal in disguise (a critical\\n'\n",
    "               '  political-economy point for the audit report).')\n",
    "print(f'  VERDICT:  {verdict}')\n",
    "print()\n",
    "print('=' * 78)\n"
])

md_post = mkmd([
    "### What this section delivers (for the audit report)\n",
    "\n",
    "- **Direct answer to the RQ** with a calibrated effect size (incremental R² with 95% CI), rather than a binary-accuracy number that is indistinguishable from majority-class prediction.\n",
    "- **Theoretical operationalization**: PISI directly instantiates Petrocik's issue ownership construct at the state level, with sentiment-weighted and unweighted variants.\n",
    "- **Honest baseline**: by partialling out 2020 margin and demographics first, we test whether Twitter discourse adds *new* information rather than echoing structural variables — a key point for the critical political-economy lens (loud Twitter voices are unevenly distributed across class/geography).\n",
    "- **Per-state residuals** flag where the model under- or over-predicts — useful for the fairness audit in §7/§8 (are large residuals concentrated in low-engagement or underrepresented states?).\n"
])

# Insert after current cell 50 (Prediction Map, end of §6), before cell 51 (§7 markdown)
new_cells = [md_header, code_features, code_matrix, code_models, code_viz, code_findings, md_post]
INSERT_AT = 51
nb['cells'] = nb['cells'][:INSERT_AT] + new_cells + nb['cells'][INSERT_AT:]

with open('the model.ipynb', 'w') as f:
    json.dump(nb, f, indent=1)

print(f'Inserted {len(new_cells)} cells at index {INSERT_AT}. New total: {len(nb["cells"])}')
